sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  allow_failures:
    - "3.7"
before_install:
  - docker pull mapd/core-os-cpu:latest
  - docker run -d --ipc=host -v /dev:/dev -p 9091:9091 --name=mapd mapd/core-os-cpu:latest
  - docker ps -a
  - export PATH="$HOME/miniconda3/bin:$PATH"
install:
  - ci/install-travis.sh
script:
  - echo "script start"
  - source activate omnisci-dev
  - pytest tests
  - flake8
