sudo: required
services:
  - docker
language: python
env:
  matrix:
    - PYTHON=3.6
    - PYTHON=3.5
    - PYTHON=2.7
before_install:
  - docker pull
  - docker run -d -p 9092:9092 -p 9091:9091 --name=mapd mapd/mapd:v3.0.0
  - docker ps -a
  - export PATH="$HOME/miniconda3/bin:$PATH"
install:
  - ci/install-travis.sh
script:
  - echo "script start"
  - source activate test-environment
  - pytest tests
  - flake8
