sudo: required
services:
  - docker
language: python
env:
  matrix:
    - PYTHON=3.6
    - PYTHON=3.5
    - PYTHON=2.7
before_install:
  - docker pull mapd/core-os-cpu
  - docker run -d -p 9091:9091 --name=mapd mapd/core-os-cpu
  - docker ps -a
  - export PATH="$HOME/miniconda3/bin:$PATH"
install:
  - ci/install-travis.sh
script:
  - echo "script start"
  - source activate test-environment
  - pytest tests
  - flake8
