# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: pymapd
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  # git_url: ../..
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  # use channel:
  #   - defaults
  #   - conda-forge
  build:
    - python
    - setuptools
    - setuptools_scm
    - cython
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - arrow-cpp >=0.5.0
    - pyarrow >=0.5.0
  run:
    - python
    - setuptools
    - numpy >=1.7.*  # [py27]
    - numpy >=1.9.*  # [py35]
    - numpy >=1.11.*  # [py36]
    - libgdf
    - pygdf
    - arrow-cpp >=0.5.0
    - pyarrow >=0.5.0
    - pandas
    - six
    - sqlalchemy
    - thrift

test:
  imports:
    - pymapd
    - mapd
    - pymapd.shm

about:
  home: https://mapd.com/
  license: Apache
  # license_file: LICENSE
  summary: Python client for the MapD GPU Database
